state: AR

links:
- name: primary
  url: https://experience.arcgis.com/experience/633006d0782b4544bd5113a314f6268a/
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(60000);
    page.done();
  renderSettings: 
    clipRectangle:
      height: 1400
      width: 1400
  message: incresing viewport size