state: IN

links:
- name: primary
  url: https://www.coronavirus.in.gov/2393.htm
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();
  message: waiting 30 sec to load IN
