state: US

links:
- name: variant_proportions
  url: https://covid.cdc.gov/covid-data-tracker/#variant-proportions

- name: published_sequences
  url: https://covid.cdc.gov/covid-data-tracker/#published-covid-sequences

- name: global_map
  url: https://covid.cdc.gov/covid-data-tracker/#global-variant-report-map
  
- name: breakthrough_cases
  url: https://www.cdc.gov/vaccines/covid-19/health-departments/breakthrough-cases.html
