state: WA

links:
- name: primary
  url: https://www.doh.wa.gov/Portals/1/Documents/1600/coronavirus/data-tables/SARS-CoV-2%20Sequencing%20Data.xlsx
  file: xlsx
  message: downloading Excel for WA primary
