state: DE

links:
- name: primary
  url: https://news.delaware.gov/tag/covid-19/
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(10000);
    await await page.evaluate(() => {
      document.evaluate("//a[contains(text(),'Weekly COVID-19 Update')]", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.setAttribute("ctpclickhere", "ctpclickhere");
    });
    page.click("a[ctpclickhere]");
    await page.waitForNavigation({
     waitUntil:"domcontentloaded"});
    await page.render.screenshot();
    page.done();
  message: click on the first weekly update link
