state: AZ

links: 
- name: primary
  url: https://www.azdhs.gov/preparedness/epidemiology-disease-control/infectious-disease-epidemiology/covid-19/dashboards/index.php
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(10000);
    page.mouse.click(615, 1208);
    await page.waitForDelay(30000);
    page.done();
  message: clicking on cases for AZ primary

- name: secondary
  url: https://tableau.azdhs.gov/views/Hospitalization/HospitalizedCOVID-19Cases?:embed=y&:showVizHome=no&:host_url=https%3A%2F%2Ftableau.azdhs.gov%2F&:embed_code_version=3&:tabs=no&:toolbar=no&:showAppBanner=false&:display_spinner=no&iframeSizedToWindow=true&:loadOrderID=3

- name: tertiary
  url: https://tableau.azdhs.gov/views/ExternalEMResourceCOVIDSpecificDashboard/InpatientCOVID-19?:embed=y&:showVizHome=no&:host_url=https%3A%2F%2Ftableau.azdhs.gov%2F&:embed_code_version=3&:tabs=yes&:toolbar=no&:showAppBanner=false&:display_spinner=no&iframeSizedToWindow=true&:loadOrderID=4
  renderSettings:
    viewport:
      width: 2400
  message: wide viewport for AZ cur hosp graph

- name: quaternary
  url: https://tableau.azdhs.gov/views/ExternalEMResourceCOVIDSpecificDashboard/VentilatorsinUseCOVID-19?%3Aembed=y&%3AshowVizHome=no&%3Ahost_url=https%3A%2F%2Ftableau.azdhs.gov%2F&%3Aembed_code_version=3&%3Atabs=yes&%3Atoolbar=no&%3AshowAppBanner=false&%3Adisplay_spinner=no&iframeSizedToWindow=true&%3AloadOrderID=1
  renderSettings:
    viewport:
      width: 2400
  message: wide viewport for AZ cur vent graph

- name: quinary
  url: https://www.azdhs.gov/preparedness/epidemiology-disease-control/infectious-disease-epidemiology/covid-19/dashboards/index.php
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(10000);
    page.mouse.click(880, 1208);
    await page.waitForDelay(30000);
    page.done();
  message: clicking on deaths for AZ quinary

- name: current_icu
  url: https://tableau.azdhs.gov/views/ExternalEMResourceCOVIDSpecificDashboard/ICUBedsforCOVID-19?%3Aembed=y&%3AshowVizHome=no&%3Ahost_url=https%3A%2F%2Ftableau.azdhs.gov%2F&%3Aembed_code_version=3&%3Atabs=yes&%3Atoolbar=no&%3AshowAppBanner=false&%3Adisplay_spinner=no&iframeSizedToWindow=true&%3AloadOrderID=1
  renderSettings:
    viewport:
      width: 2400
  message: wide viewport for AZ cur icu graph
  
- name: pcr_tests_specimens
  url: https://tableau.azdhs.gov/views/ELRv2testlevelandpeopletested/TestsConducted?%3AisGuestRedirectFromVizportal=y&%3Aembed=y&Choose%20Test%20Type=Diagnostic
  
- name: serology_tests_specimens
  url: https://tableau.azdhs.gov/views/ELRv2testlevelandpeopletested/TestsConducted?%3AisGuestRedirectFromVizportal=y&%3Aembed=y&Choose%20Test%20Type=Serology


