state: CA

links: 
- name: primary
  url: https://update.covid19.ca.gov
  renderSettings: 
    viewport:
      height: 3000
      width: 1400
  message: using viewport height 3000 for CA

- name: secondary
  url: https://public.tableau.com/profile/ca.open.data#!/vizhome/COVID-19CasesDashboardv2_0/CaseStatistics

- name: tertiary
  url: https://public.tableau.com/views/COVID-19HospitalsDashboard/Hospitals?:embed=y&:showVizHome=no
  
- name: quaternary 
  url: https://public.tableau.com/profile/ca.open.data#!/vizhome/COVID-19CasesDashboardv2_0/TestingStatistics


