state: CO

links: 
- name: primary
  url: https://public.tableau.com/views/Colorado_COVID19_Data/CO_Hospital?%3Aembed=y&%3AshowVizHome=no
  renderSettings:
    viewport:
      width: 1400
      height: 3000
  message: using viewport width 1400 for CO

- name: secondary
  url: https://services3.arcgis.com/66aUo8zsujfVXRIT/arcgis/rest/services/colorado_covid19_laboratory_positivity_data/FeatureServer/0/query?where=Metric%3D%27Number+of+positive+tests%27+AND+Desc_+LIKE+%27Daily+COVID-19+Antibody%25%27&outStatistics=%5B%7B%27statisticType%27%3A+%27max%27%2C+%27onStatisticField%27%3A+%27Attr_Date%27%7D%2C+%7B%27statisticType%27%3A+%27sum%27%2C+%27onStatisticField%27%3A+%27Value%27%2C+%27outStatisticFieldName%27%3A+%27antibody_pos%27%7D%5D
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();
  message: wait for CO dash to avoid blank screenshots

- name: tertiary
  url: https://services3.arcgis.com/66aUo8zsujfVXRIT/arcgis/rest/services/colorado_covid19_laboratory_positivity_data/FeatureServer/0/query?where=Metric%3D%27Number+of+negative+tests%27+AND+Desc_+LIKE+%27Daily+COVID-19+Antibody%25%27&outStatistics=%5B%7B%27statisticType%27%3A+%27max%27%2C+%27onStatisticField%27%3A+%27Attr_Date%27%7D%2C+%7B%27statisticType%27%3A+%27sum%27%2C+%27onStatisticField%27%3A+%27Value%27%2C+%27outStatisticFieldName%27%3A+%27antibody_neg%27%7D%5D

- name: quaternary
  url: https://covid19.colorado.gov/data
  overseerScript: |
    await page.waitForSelector("a.ckeditor-accordion-toggler");
    await page.evaluate(() => {
      document.evaluate("//a[contains(text(),'Hospital')]", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.setAttribute("ctpclickhere", "ctpclickhere");
    });
    page.click("a[ctpclickhere]");
    await page.evaluate(() => {
      document.evaluate("//a[contains(text(),'Case')]", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.setAttribute("ctpclickhere1", "ctpclickhere1");
    });
    page.click("a[ctpclickhere1]");
    page.done();
  renderSettings: 
    viewport:
      width: 2000
  message: clicking on case and hospital data summary toggles for CO quinary

