state: GA

links: 
- name: primary
  url: https://dph.georgia.gov/covid-19-daily-status-report

- name: secondary
  url: https://www.arcgis.com/apps/opsdashboard/index.html#/e40c39564f724af7bfe8fd5d88deadb6
