state: GU

links: 
- name: primary
  url: http://dphss.guam.gov/covid-19/

- name: secondary
  url: https://drive.google.com/file/d/1FVW6sNbdgyV5-CYkOorYvOGivkmOED8t/view

- name: tertiary
  url: https://drive.google.com/file/d/1n-vrUGzEzs7rjcxXBFEbIMmeUQykuyO9/view
  renderSettings: 
    viewport:
      height: 5000

- name: quaternary
  url: https://ghs.guam.gov/coronavirus-covid-19
  overseerScript: |
    page.manualWait();
    await page.waitForSelector("a[href*=\"/jic-release-no-\"]");
    page.click("a[href*=\"/jic-release-no-\"]");
    await page.waitForNavigation({
     waitUntil:"domcontentloaded"});
    await page.render.screenshot();
    page.done();
  message: clicking on latest GU JIC release
