state: IA

links: 
- name: primary
  url: https://coronavirus.iowa.gov/
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();
  renderSettings: 
    viewport:
      height: 3000
      width: 1400

- name: secondary
  url: https://coronavirus.iowa.gov/pages/case-counts
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(60000);
    page.done();

- name: tertiary
  url: https://coronavirus.iowa.gov/pages/rmcc-data
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(45000);
    page.done();

- name: quaternary
  url: https://coronavirus.iowa.gov/pages/serology-testing
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(45000);
    page.done();

