state: IA

links: 
- name: primary
  url: https://coronavirus.iowa.gov/
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(60000);
    page.done();
  renderSettings: 
    viewport:
      height: 3000
      width: 1400
  requestSettings:
    maxWait: 90000
  message: adding manual wait and using viewport height 3000 for IA

- name: secondary
  url: https://coronavirus.iowa.gov/pages/case-counts
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(80000);
    page.done(); 
  requestSettings: 
    maxWait: 90000
  message: adding manual wait for IA secondary

- name: tertiary
  url: https://coronavirus.iowa.gov/pages/rmcc-data
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(80000);
    page.done();
  requestSettings: 
    maxWait: 90000
  message: wait for IA tertiary

- name: quaternary
  url: https://coronavirus.iowa.gov/pages/serology-testing
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(80000);
    page.done();
  requestSettings: 
    maxWait: 90000
  message: wait for IA quaternary

