state: IN

links: 
- name: primary
  url: https://www.in.gov/isdh/28470.htm
  overseerScript: |
    page.manualWait();
    await page.waitForSelector("#prefix-dismissButton");
    page.click("#prefix-dismissButton");
    await page.waitForFunction(()=>document.querySelector("#main-content").textContent!=="");
    page.done();
  renderSettings: 
    viewport:
      height: 13000
      width: 1400

- name: secondary
  url: https://www.regenstrief.org/covid-dashboard/
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();

- name: tertiary
  url: https://hub.mph.in.gov/dataset/covid-19-beds-and-vents/resource/882a7426-886f-48cc-bbe0-a8d14e3012e4/view/05961851-c7ab-4ac7-92bf-fdf9881ecdab
  overseerScript: |
    page.manualWait();
    await page.waitForSelector("span.slick-column-name");
    page.click("span.slick-column-name", {
      button: "right" });
    await page.waitForSelector("#slick-option-autoresize");
    page.click("#slick-option-autoresize");
    page.mouse.move(1, 1);
    await page.waitForDelay(5000);
    page.done();

