state: KS

links: 
- name: primary
  url: https://www.coronavirus.kdheks.gov/160/COVID-19-in-Kansas

- name: secondary
  url: https://public.tableau.com/views/COVID-19TableauVersion2/HospitalCapacity?%3Aembed=y&%3AshowVizHome=no

- name: tertiary
  url: https://public.tableau.com/views/COVID-19TableauVersion2/TestingRates?%3Aembed=y&%3AshowVizHome=no

- name: quaternary
  url: https://public.tableau.com/views/COVID-19TableauVersion2/HospitalSummary?%3Aembed=y&%3AshowVizHome=no

