state: KY

links: 
- name: primary
  url: https://govstatus.egov.com/kycovid19

- name: secondary
  url: https://chfs.ky.gov/agencies/dph/covid19/COVID19DailyReport.pdf
  message: downloading PDF for KY secondary

