state: MO

links: 
- name: primary
  url: https://showmestrong.mo.gov/data/statewide-public-health/
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();
  message: waiting for MO primary

- name: secondary
  url: https://showmestrong.mo.gov/public-healthcare-testing/
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();
  message: waiting for MO secondary

- name: tertiary
  url: https://showmestrong.mo.gov/public-healthcare/
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();
  message: waiting for MO tertiary

- name: quaternary
  url: https://showmestrong.mo.gov/public-healthcare-testing/
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(10000);
    await page.mouse.move(774, 1030);
    await page.mouse.click(774, 1030);
    await page.waitForDelay(20000);
    page.done();
  message: positive PCR for MO quaternary

- name: quinary
  url: https://showmestrong.mo.gov/public-healthcare-testing/
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(10000);
    await page.mouse.move(774, 1124);
    await page.waitForDelay(20000);
    page.done();
  message: positive Serology for MO quinary

- name: antigen_positive
  url: https://showmestrong.mo.gov/public-healthcare-testing/
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(20000);
    await page.mouse.click(774, 1184);
    await page.waitForDelay(5000);
    page.done();
  message: positive Antigen for MO
