state: MP

links: 
- name: primary
  url: https://cnmichcc.maps.arcgis.com/apps/opsdashboard/index.html#/4061b674fc964efe84f7774b7979d2b5

- name: secondary
  url: https://services8.arcgis.com/zkkZCub5I6ydvXQj/ArcGIS/rest/services/Coronavirus_PublicDashboardView/FeatureServer/3/query?where=1%3D1&outStatistics=%5B%7B%27statisticType%27%3A+%27max%27%2C+%27onStatisticField%27%3A+%27reportdt%27%7D%2C+%7B%27statisticType%27%3A+%27sum%27%2C+%27onStatisticField%27%3A+%27confirmedcases%27%7D%2C+%7B%27statisticType%27%3A+%27sum%27%2C+%27onStatisticField%27%3A+%27totalspeccnmi%27%7D%2C+%7B%27statisticType%27%3A+%27sum%27%2C+%27onStatisticField%27%3A+%27deaths%27%7D%2C+%7B%27statisticType%27%3A+%27sum%27%2C+%27onStatisticField%27%3A+%27recovered%27%7D%2C+%7B%27statisticType%27%3A+%27sum%27%2C+%27onStatisticField%27%3A+%27hospitalized%27%7D%5D

- name: tertiary
  url: https://cnmichcc.maps.arcgis.com/apps/opsdashboard/index.html#/4061b674fc964efe84f7774b7979d2b5
  overseerScript: |
    page.manualWait();
    await page.waitForSelector(".tab-title:nth-of-type(2)");
    page.click(".tab-title:nth-of-type(2)");
    await page.waitForDelay(30000);
    page.done();
  message: custom click logic for MP tertiary dashboard

- name: quaternary
  url: https://cnmichcc.maps.arcgis.com/apps/opsdashboard/index.html#/4061b674fc964efe84f7774b7979d2b5
  overseerScript: |
    page.manualWait();
    await page.waitForSelector(".tab-title:nth-of-type(3)");
    page.click(".tab-title:nth-of-type(3)");
    await page.waitForDelay(30000);
    page.done();
  message: custom click logic for MP quaternary dashboard

