state: NC

links: 
- name: primary
  url: https://www.ncdhhs.gov/covid-19-case-count-nc

- name: secondary
  url: https://files.nc.gov/covid/documents/dashboard/Weekly-COVID19-Patients-Presumed-to-be-Recovered.pdf
  message: downloading pdf

- name: tertiary
  url: https://public.tableau.com/views/NCDHHS_COVID-19_Dashboard_HospitalizationsE/Hospitalizations?:embed=y&:showVizHome=no&:host_url=https%3A%2F%2Fpublic.tableau.com%2F&:embed_code_version=3&:tabs=no&:toolbar=no&:animate_transition=yes&:display_static_image=no&:display_spinner=no&:display_overlay=yes&:display_count=no&:language=en&publish=yes&:loadOrderID=0
  overseerScript: |
    page.manualWait();
    await page.waitForSelector("#\\[Parameters\\]\\.\\[Parameter\\ 7\\]_2 input");
    page.click("#\\[Parameters\\]\\.\\[Parameter\\ 7\\]_2 input");
    await page.waitForDelay(10000);
    page.done();
  message: crazy clicking for NC tertiary, waiting 10 seconds

- name: quaternary
  url: https://public.tableau.com/views/NCDHHS_COVID-19_Dashboard_Cases_County/NCDHHS_Dashboard_Cases2?:embed=y&:showVizHome=no&:host_url=https%3A%2F%2Fpublic.tableau.com%2F&:embed_code_version=3&:tabs=no&:toolbar=no&:animate_transition=yes&:display_static_image=no&:display_spinner=no&:display_overlay=yes&:display_count=yes&:language=en&publish=yes&:loadOrderID=0
  overseerScript: |
    page.manualWait();
    await page.waitForSelector("a[title='DEATHS by Date of Death'");
    await page.waitForDelay(5000);
    await page.evaluate(() => {
      document.querySelector("a[title='DEATHS by Date of Death'").parentElement.firstChild.setAttribute("ctpclickhere", "ctpclickhere");
    });
    await page.waitForDelay(1000);
    page.click("[ctpclickhere]");
    await page.waitForDelay(10000);
    page.done();
  message: clicking on "deaths by date of death".

