state: ND

links: 
- name: primary
  url: https://www.health.nd.gov/diseases-conditions/coronavirus/north-dakota-coronavirus-cases
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(150000);
    page.done();
  requestSettings:
    maxWait: 180000
  message: waiting for 150 seconds to load ND

- name: secondary
  url: https://app.powerbigov.us/view?r=eyJrIjoiZDcwNDA0ODAtZWU0OC00NDhmLWIzYTMtOTBmZDBkNjNkYTg3IiwidCI6IjJkZWEwNDY0LWRhNTEtNGE4OC1iYWUyLWIzZGI5NGJjMGM1NCJ9&pageName=ReportSection023f3fc1641deaab2bb0
  overseerScript: |
    await page.waitForDelay(10000);
    await page.waitForSelector("i[title='Next Page']");
    page.click("i[title='Next Page']");
    await page.waitForDelay(5000);
    page.click("i[title='Next Page']");
    await page.waitForDelay(5000);
    page.click("i[title='Next Page']");
    await page.waitForDelay(15000);
    page.done();;
  requestSettings:
    maxWait: 180000
  message: selecting Hospitalizations tab for ND secondary

