state: ND

links: 
- name: primary
  url: https://www.health.nd.gov/diseases-conditions/coronavirus/north-dakota-coronavirus-cases
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(150000);
    page.done();
  requestSettings:
    maxWait: 180000
  message: waiting for 150 seconds to load ND

- name: secondary
  url: https://www.health.nd.gov/diseases-conditions/coronavirus/north-dakota-coronavirus-cases
  overseerScript: |
    await page.waitForDelay(10000);
    await page.waitForSelector("i[title='Next Page']");
    await page.click("i[title='Next Page']");
    await page.waitForDelay(5000);
    await page.click("i[title='Next Page']");
    await page.waitForDelay(5000);
    await page.click("i[title='Next Page']");
    await page.waitForDelay(60000);
    page.done();
  requestSettings:
    maxWait: 180000
  message: selecting Hospitalizations tab for ND secondary

