state: NE

links: 
- name: primary
  url: https://experience.arcgis.com/experience/ece0db09da4d4ca68252c3967aa1e9dd
  renderSettings: 
    viewport:
      height: 5000
      width: 1400
  message: using viewport height 5000 for NE

- name: secondary
  url: https://gis.ne.gov/enterprise/rest/services/Covid19MapV5/MapServer/11/query?where=1%3D1&outFields=%2A&orderByFields=LAB_REPORT_DATE+desc&resultRecordCount=1&f=json

- name: tertiary
  url: https://experience.arcgis.com/experience/ece0db09da4d4ca68252c3967aa1e9dd

- name: quaternary
  url: https://experience.arcgis.com/experience/ece0db09da4d4ca68252c3967aa1e9dd

- name: quinary
  url: https://experience.arcgis.com/experience/ece0db09da4d4ca68252c3967aa1e9dd

