state: NH

links: 
- name: primary
  url: https://www.dhhs.nh.gov/dphs/cdcs/2019-ncov.htm

- name: secondary
  url: https://www.nh.gov/covid19/documents/case-summary.pdf
  file: pdf
  message: downloading pdf

- name: tertiary
  url: https://www.nh.gov/covid19/dashboard/overview.htm#dash

- name: quaternary
  url: https://nh.gov/t/DHHS/views/COVID19TrendsDashboard/TrendsDashboard?:isGuestRedirectFromVizportal=y&:embed=y
  overseerScript: |
    page.manualWait();
    await page.waitForSelector("a[title='Antibody Tests - Test Based'");
    await page.waitForDelay(5000);
    await page.evaluate(() => {
      document.querySelector("a[title='Antibody Tests - Test Based'").parentElement.firstChild.setAttribute("ctpclickhere", "ctpclickhere");
    });
    await page.waitForDelay(1000);
    page.click("[ctpclickhere]");
    await page.waitForDelay(10000);
    page.done();
  message: clicking on 'Antibody Tests - Test Based'.

