state: NJ

links: 
- name: primary
  url: https://covid19.nj.gov/#live-updates
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    await page.waitForSelector("button#overlay-close");
    page.click("button#overlay-close");
    await page.waitForDelay(30000);
    page.done();
  message: close the overlay

- name: secondary
  url: https://njhealth.maps.arcgis.com/apps/MapSeries/index.html?appid=50c2c6af93364b4da9c0bf6327c04b45&folderid=e5d6362c0f1f4f9684dc650f00741b24
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    await page.waitForSelector("button[aria-label='Go to entry 3: Hospital Census']");
    page.click("button[aria-label='Go to entry 3: Hospital Census']");
    await page.waitForDelay(30000);
    page.done();
  message: click on 'Hospital Census' tab for NJ secondary

- name: tertiary
  url: https://njhealth.maps.arcgis.com/apps/opsdashboard/index.html#/81a17865cb1a44db92eb8eb421703635
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();
  message: waiting 30 sec to load NJ tertiary

- name: quaternary
  url: https://services7.arcgis.com/Z0rixLlManVefxqY/arcgis/rest/services/PPE_Capacity/FeatureServer/0/query?where=survey_period%3E%3Dtimestamp+%272020-04-27+07%3A00%3A00%27+AND+structure_measure_identifier+LIKE+%27%25ischarge%25Excluding+Deaths%25%27&outStatistics=%5B%7B%27statisticType%27%3A+%27sum%27%2C+%27onStatisticField%27%3A+%27Value%27%2C+%27outStatisticFieldName%27%3A+%27recoveries%27%7D%5D

