state: NV

links: 
- name: primary
  url: https://app.powerbigov.us/view?r=eyJrIjoiMjA2ZThiOWUtM2FlNS00MGY5LWFmYjUtNmQwNTQ3Nzg5N2I2IiwidCI6ImU0YTM0MGU2LWI4OWUtNGU2OC04ZWFhLTE1NDRkMjcwMzk4MCJ9

- name: secondary
  url: https://app.powerbigov.us/view?r=eyJrIjoiMjA2ZThiOWUtM2FlNS00MGY5LWFmYjUtNmQwNTQ3Nzg5N2I2IiwidCI6ImU0YTM0MGU2LWI4OWUtNGU2OC04ZWFhLTE1NDRkMjcwMzk4MCJ9&pageName=ReportSection713122d051caa3096e41

- name: tertiary
  url: https://app.powerbigov.us/view?r=eyJrIjoiMjA2ZThiOWUtM2FlNS00MGY5LWFmYjUtNmQwNTQ3Nzg5N2I2IiwidCI6ImU0YTM0MGU2LWI4OWUtNGU2OC04ZWFhLTE1NDRkMjcwMzk4MCJ9&pageName=ReportSection966ce53550e53608e0a6
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.mouse.move(1436, 591);
    await page.waitForDelay(8000);
    page.done();
  renderSettings:
    viewport:
      width: 2000
  message: hospitalizations for NV tertiary

- name: quaternary
  url: https://app.powerbigov.us/view?r=eyJrIjoiMjA2ZThiOWUtM2FlNS00MGY5LWFmYjUtNmQwNTQ3Nzg5N2I2IiwidCI6ImU0YTM0MGU2LWI4OWUtNGU2OC04ZWFhLTE1NDRkMjcwMzk4MCJ9&pageName=ReportSection966ce53550e53608e0a6
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.mouse.move(1440, 890);
    await page.waitForDelay(10000);
    page.done();
  renderSettings:
    viewport:
      width: 2000
  message: ICU and ventilator usage for NV quaternary

