state: NY

links: 
- name: primary
  url: https://coronavirus.health.ny.gov/county-county-breakdown-positive-cases
  renderSettings: 
    viewport:
      width: 2000
  message: using viewport width 2000 for NY

- name: secondary
  url: https://covid19tracker.health.ny.gov/views/NYS-COVID19-Tracker/NYSDOHCOVID-19Tracker-Fatalities?%3Aembed=yes&%3Atoolbar=no&%3Atabs=n
  renderSettings: 
    viewport:
      width: 5000
  message: using viewport width 5000 for NY

- name: tertiary
  url: https://www.governor.ny.gov/keywords/coronavirus
  overseerScript: |
    page.manualWait();
    await page.waitForSelector("a[href*=\"/news/governor-cuomo-updates-new-yorkers-states-progress-during-covid-19-pandemic-\"]");
    page.click("a[href*=\"/news/governor-cuomo-updates-new-yorkers-states-progress-during-covid-19-pandemic-\"]");
    await page.waitForNavigation({
     waitUntil:"domcontentloaded"});
    await page.render.screenshot();
    page.done();
  message: click on the first "gov cuomo updates..." link, which should be the latest press release

- name: quaternary
  url: https://forward.ny.gov/daily-hospitalization-summary-region
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(10000);
    page.mouse.click(1060, 1100);
    await page.waitForDelay(10000);
    page.done();
  message: hover over hospitalizations for NY quaternary

- name: quinary
  url: https://forward.ny.gov/daily-hospitalization-summary-region
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(10000);
    page.mouse.click(1060, 1174);
    await page.waitForDelay(10000);
    page.done();
  message: hover over ICU for NY quinary

