state: OH

links: 
- name: primary
  url: https://coronavirus.ohio.gov/wps/portal/gov/covid-19/dashboards/overview/

- name: secondary
  url: https://coronavirus.ohio.gov/wps/portal/gov/covid-19/dashboards/key-metrics/cases
