state: PR

links: 
- name: primary
  url: https://services5.arcgis.com/klquQoHA0q9zjblu/ArcGIS/rest/services/Datos_Totales_View7/FeatureServer/0/query?where=1%3D1&outFields=T_Muertes_COVID_RD%2CT_Fatalidades%2CT_Muertes_Combinadas%2CT_Pacientes_Int_Covid%2CT_Vent_Covid%2CT_Serologicos_Pos%2CT_Casos_Unicos%2CT_Molecular_Pos%2CT_Fatalidades%2CT_Hospitalizados%2CT_Recuperados

- name: secondary
  url: https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/3bfb64c9a91944bc8c41edd8ff27e6df
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();
  message: wait 30 seconds to load PR secondary

- name: tertiary
  url: http://www.salud.gov.pr/Pages/coronavirus.aspx

- name: quaternary
  url: https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/3bfb64c9a91944bc8c41edd8ff27e6df
  overseerScript: |
    await page.waitForNavigation({
     waitUntil:"domcontentloaded"});
    await page.waitForSelector("#ember961");
    page.click("#ember961");
    page.done();
  message: click button for PR recoveries ("Convalecientes")

- name: quinary
  url: https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/3bfb64c9a91944bc8c41edd8ff27e6df
  overseerScript: |
    await page.waitForNavigation({
     waitUntil:"domcontentloaded"});
    await page.waitForSelector("#ember827");
    page.click("#ember827");
    page.done();
  message: click button for PR confirmed deaths ("Confirmados")

- name: deaths_probable
  url: https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/3bfb64c9a91944bc8c41edd8ff27e6df
  overseerScript: |
    await page.waitForNavigation({
     waitUntil:"domcontentloaded"});
    await page.waitForSelector("#ember827");
    page.click("#ember827");
    page.manualWait();
    await page.waitForDelay(5000);
    page.click("#ember827");
    await page.waitForDelay(5000);
    page.done();
  message: click button twice for PR probable deaths ("Probables")

- name: pr_statistics_site
  url: https://covid19datos.salud.gov.pr
