state: PR

links: 
- name: primary
  url: https://estadisticas.pr/en/covid-19

- name: secondary
  url: https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/3bfb64c9a91944bc8c41edd8ff27e6df

- name: tertiary
  url: http://www.salud.gov.pr/Pages/coronavirus.aspx

- name: quaternary
  url: https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/3bfb64c9a91944bc8c41edd8ff27e6df
  overseerScript: |
    await page.waitForNavigation({
     waitUntil:"domcontentloaded"});
    await page.waitForSelector("#ember906");
    page.click("#ember906");
    page.done();

- name: quinary
  url: https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/3bfb64c9a91944bc8c41edd8ff27e6df
  overseerScript: |
    await page.waitForNavigation({
     waitUntil:"domcontentloaded"});
    await page.waitForSelector("#ember772");
    page.click("#ember772");
    page.done();

