state: SD

links: 
- name: primary
  url: https://doh.sd.gov/COVID/Dashboard.aspx
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(90000);
    page.done();
  message: waiting 90 sec to load SD

- name: secondary
  url: https://doh.sd.gov/COVID/Dashboard.aspx
  overseerScript: |
    await page.waitForDelay(10000);
    await page.waitForSelector("i[title='Next Page']");
    page.click("i[title='Next Page']");
    await page.waitForDelay(5000);
    page.click("i[title='Next Page']");
    await page.waitForDelay(5000);
    page.click("i[title='Next Page']");
    await page.waitForDelay(25000);
    page.done();
  requestSettings:
    maxWait: 180000
  message: navigating to Hospital Capacity tab of dash for secondary

- name: tertiary
  url: https://doh.sd.gov/COVID/Dashboard.aspx
  overseerScript: |
    await page.waitForDelay(25000);
    await page.waitForSelector("i[title='Next Page']");
    await page.evaluate(() => {
      document.evaluate("//span[contains(text(),'Tables')]", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.setAttribute("ctpclickhere", "ctpclickhere");
    });
    page.click("span[ctpclickhere]");
    await page.waitForDelay(25000);
    page.done();
  message: navigating to "tables" tab of dash
