state: SD

links: 
- name: primary
  url: https://doh.sd.gov/COVID/Dashboard.aspx
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(90000);
    page.done();
  message: waiting 90 sec to load SD

