state: TN

links: 
- name: primary
  url: https://www.tn.gov/health/cedep/ncov.html

- name: secondary
  url: https://apps.health.tn.gov/AEM_embed/TDH-2019-Novel-Coronavirus-Epi-and-Surveillance.pdf#toolbar=0
  file: pdf
  message: downloading PDF for TN secondary

- name: tertiary
  url: https://data.tn.gov/t/Public/views/HospitalizedPatients/HospitalizedPatients?:embed=y
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(10000);
    page.mouse.move(1087, 542);
    await page.waitForDelay(15000);
    page.done();
  message: confirmed hospitalizations for TN tertiary

- name: quaternary
  url: https://www.tn.gov/content/tn/health/cedep/ncov/data.html
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(150000);
    page.done();
  requestSettings:
    maxWait: 180000
  message: dash for TN quaternary

- name: quinary
  url: https://data.tn.gov/t/Public/views/HospitalizedPatients/HospitalizedPatients?:embed=y
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(6000);
    await page.waitForSelector("#tableau_base_widget_ParameterControl_0 div[role='radio']:nth-child(2) input");
    page.click("#tableau_base_widget_ParameterControl_0 div[role='radio']:nth-child(2) input");
    await page.waitForDelay(5000);
    page.mouse.move(1087, 542);
    await page.waitForDelay(15000);
    page.done();
  message: pending hospitalizations for TN quinary

