state: TX

links: 
- name: primary
  url: https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();
  message: waiting 30 sec to load TX

- name: secondary
  url: https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/0d8bdf9be927459d9cb11b9eaef6101f

- name: tertiary
  url: https://www.dshs.texas.gov/coronavirus/TexasCOVID-19HospitalizationsOverTimebyTSA.xlsx
  file: xlsx
  message: downloading Excel for TX tertiary

- name: quaternary
  url: https://www.dshs.texas.gov/coronavirus/TexasCOVID19CaseCountData.xlsx
  file: xlsx
  message: downloading cases excel for TX quaternary
  
- name: quinary
  url: https://services5.arcgis.com/ACaLB9ifngzawspq/ArcGIS/rest/services/TX_DSHS_COVID19_TestData_Service/FeatureServer/3/query?where=1%3D1&outFields=%2A&cacheHint=False



