state: US

links:
- name: testing_cdc
  url: https://covid.cdc.gov/covid-data-tracker/#testing_positivity7day
  overseerScript: |
    page.manualWait();
    await page.waitForSelector("#testing-table-header-icon");
    page.click("#testing-table-header-icon");
    await page.waitForDelay(1000);
    page.click("#btnUSTableExport");
    await page.waitForDelay(5000);
    page.done();
  message: expand data table on CDC testing website

- name: ctp_long_formulas
  renderSettings:
    viewport:
      height: 10000
  url: https://docs.google.com/spreadsheets/d/1WVnWoQ28lQgkvuVwIaY63k8AbjxSrxkdYzuYCT-CL6M/edit?usp=sharing
  message: screenshot of CTP long formulas