state: UT

links: 
- name: primary
  url: https://coronavirus.utah.gov/case-counts/
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(50000);
    page.done();
  message: UT dashboard

- name: secondary
  url: https://coronavirus-dashboard.utah.gov/hosp.html
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(50000);
    page.done();
  message: UT hosp dashboard
