state: VT

links: 
- name: primary
  url: https://experience.arcgis.com/experience/85f43bd849e743cb957993a545d17170

- name: secondary
  url: https://www.healthvermont.gov/response/coronavirus-covid-19/current-activity-vermont#dashboard

- name: tertiary
  url: https://experience.arcgis.com/experience/85f43bd849e743cb957993a545d17170
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(20000);
    await page.evaluate(() => {
      document.evaluate("//div[text()='Cases and Deaths']", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.setAttribute("ctpclickhere", "ctpclickhere");
    });
    page.click("div[ctpclickhere]");
    await page.waitForDelay(20000);
    page.done();
  renderSettings: 
    viewport:
      width: 2000
  message: clicking on Cases and Deaths Tab for VT tertiary

