state: WI

links: 
- name: primary
  url: https://www.dhs.wisconsin.gov/covid-19/data.htm

- name: secondary
  url: https://www.dhs.wisconsin.gov/covid-19/hosp-data.htm

- name: tertiary
  url: https://bi.wisconsin.gov/t/DHS/views/PercentofconfirmedprobableCOVID-19casesby-group-MOBILE/CaseDB2/butleoljdl@accounts.wistate.us/ed25311e-7f8a-4c7d-aee8-97b28850f0ac?:embed=y&:display_spinner=no&:showAppBanner=false&:embed_code_version=3&:loadOrderID=4&:display_count=n&:showVizHome=n&:origin=viz_share_link
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(6000);
    await page.waitForSelector("#tableau_base_widget_ParameterControl_1 div[role='radio']:nth-child(2) input");
    page.click("#tableau_base_widget_ParameterControl_1 div[role='radio']:nth-child(2) input");
    await page.waitForDelay(5000);
    page.done();
  message: wi probables

- name: quaternary
  url: https://bi.wisconsin.gov/t/DHS/views/PercentofCOVID-19deathsby-group-MOBILE/DeathDB2?:embed_code_version=3&:embed=y&:loadOrderID=2&:display_spinner=no&:showAppBanner=false&:display_count=n&:showVizHome=n&:origin=viz_share_link
  message: download CSV for testing data

- name: quinary
  url: https://bi.wisconsin.gov/t/DHS/views/PercentofCOVID-19deathsby-group-MOBILE/DeathDB2?:embed_code_version=3&:embed=y&:loadOrderID=2&:display_spinner=no&:showAppBanner=false&:display_count=n&:showVizHome=n&:origin=viz_share_link

