state: WV

links: 
- name: primary
  url: https://dhhr.wv.gov/Coronavirus%20Disease-COVID-19/Pages/default.aspx
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(90000);
    page.done();

- name: secondary
  url: https://dhhr.wv.gov/Coronavirus%20Disease-COVID-19/Pages/default.aspx
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(20000);
    await page.evaluate(() => {
      document.evaluate("//button/span[contains(text(),'Hospital')]", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.setAttribute("ctpclickhere", "ctpclickhere");
    });
    page.click("span[ctpclickhere]");
    await page.waitForDelay(10000);
    page.done();

- name: tertiary
  url: https://dhhr.wv.gov/Coronavirus%20Disease-COVID-19/Pages/default.aspx
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(20000);
    await page.evaluate(() => {
      document.evaluate("//button/span[contains(text(),'Includes Probable and Confirmed Cases (Click to View')]", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.setAttribute("ctpclickhere", "ctpclickhere");
    });
    page.click("span[ctpclickhere]");
    await page.waitForDelay(10000);
    page.done();

- name: quaternary
  url: https://dhhr.wv.gov/Coronavirus%20Disease-COVID-19/Pages/default.aspx

