state: AK

links: 
- name: primary
  url: https://coronavirus-response-alaska-dhss.hub.arcgis.com/
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();
  message: waiting 30 seconds for AK

