state: CA

links: 
- name: primary
  url: https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/SNFsCOVID_19.aspx
  renderSettings: 
    viewport:
      height: 8500
      width: 1400

- name: secondary
  url: https://www.cdss.ca.gov/#covid19

