state: MS

links: 
- name: primary
  url: https://msdh.ms.gov/msdhsite/_static/resources/8578.pdf
  file: pdf
  message: downloading pdf for MS

- name: secondary
  url: https://msdh.ms.gov/msdhsite/_static/resources/8660.pdf
  file: pdf
  message: downloading pdf for MS secondary

- name: tertiary
  url: https://msdh.ms.gov/msdhsite/_static/resources/8659.pdf
  file: pdf
  message: downloading pdf for MS tertiary

