state: NC

links: 
- name: primary
  url: https://covid19.ncdhhs.gov/dashboard/outbreaks-and-clusters

- name: secondary
  url: https://files.nc.gov/covid/documents/dashboard/Weekly-COVID19-Ongoing-Outbreaks.pdf

