state: PA

links: 
- name: primary
  url: https://www.health.pa.gov/topics/disease/coronavirus/Pages/LTCF-Data.aspx
  renderSettings: 
    viewport:
      height: 7000
      width: 1400
  message: using viewport height 7000 for PA

- name: secondary
  url: https://www.health.pa.gov/topics/Documents/Diseases%20and%20Conditions/COVID-19%20LTCF%20Data_7-20-2020.xlsx
  file: xlsx
  message: downloading xlsx for PA secondary

- name: tertiary
  url: https://www.health.pa.gov/topics/Documents/Diseases%20and%20Conditions/DHS%20Facility%20COVID-19%20Totals_7-20-2020.xlsx
  file: xlsx
  message: downloading xlsx for PA tertiary

