state: TX

links: 
- name: primary
  url: https://apps.hhs.texas.gov/providers/directories/Texas_Nursing_Facilities_COVID_Status.xls

- name: secondary
  url: https://apps.hhs.texas.gov/providers/directories/Texas_Assisted_Living_Facilities_COVID_Status.xls

