state: UT

links: 
- name: primary
  url: https://coronavirus-dashboard.utah.gov/#outbreaks
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(40000);
    page.done();
  renderSettings: 
    clipRectangle:
      height: 1500
      width: 1400

