state: WI

links: 
- name: primary
  url: https://www.dhs.wisconsin.gov/covid-19/cases.htm

- name: secondary
  url: https://www.dhs.wisconsin.gov/covid-19/deaths.htm

- name: tertiary
  url: https://www.dhs.wisconsin.gov/covid-19/investigations.htm

