state: AZ

links:
- name: vaccine
  url: https://www.azdhs.gov/documents/preparedness/epidemiology-disease-control/infectious-disease-epidemiology/novel-coronavirus/vaccine-phases.pdf
  file: pdf
  message: downloading PDF
