state: GA

links:
- name: vaccine
  url: https://experience.arcgis.com/experience/3d8eea39f5c1443db1743a4cb8948a9c/
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();
  message: waiting 30 seconds for GA vaccine
