state: ID

links:
- name: vaccine
  url: https://coronavirus.idaho.gov/
  renderSettings: 
    viewport:
      height: 2500
      
- name: vaccine_secondary
  url: https://public.tableau.com/profile/idaho.division.of.public.health#!/vizhome/COVID-19VaccineDataDashboard/Residence
    overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();
  message: waiting 30 sec to load ID vaccine
