state: IL

links:
- name: vaccine
  url: https://www.dph.illinois.gov/covid19/vaccinedata?county=Illinois
  
- name: chicago-vaccine
  url: https://data.cityofchicago.org/resource/553k-3xzc.csv
  file: csv
