state: MN

links:
- name: vaccine
  url: https://www.health.state.mn.us/diseases/coronavirus/vaccine/stats/provider.html
  overseerScript: |
     page.manualWait();
     await page.waitForDelay(60000);
     page.done();
  message: waiting 60 sec to load MN vaccine
   
- name: vaccine_secondary
  url: https://mn.gov/covid19/vaccine/data/index.jsp
  overseerScript: |
     page.manualWait();
     await page.waitForDelay(60000);
     page.done();
  message: waiting 60 sec to load MN vaccine
