state: MN

links:
- name: vaccineproviders
  url: https://www.health.state.mn.us/diseases/coronavirus/vaccine/stats/provider.html
  overseerScript: |
     page.manualWait();
     await page.waitForDelay(60000);
     page.done();
  message: waiting 60 sec to load MN vaccine
   
- name: vaccinedistribution
  url: https://www.health.state.mn.us/diseases/coronavirus/vaccine/stats/distrib.html
  overseerScript: |
     page.manualWait();
     await page.waitForDelay(60000);
     page.done();
  message: waiting 60 sec to load MN vaccine
   
- name: vaccineadmin
  url: https://health.state.mn.us/diseases/coronavirus/vaccine/stats/admin.html#agend1
  overseerScript: |
     page.manualWait();
     await page.waitForDelay(60000);
     page.done();
  message: waiting 60 sec to load MN vaccine
