state: NY

links:

- name: vaccine
  url: https://covid19vaccine.health.ny.gov/covid-19-vaccine-tracker
  overseerScript: |
     page.manualWait();
     await page.waitForDelay(60000);
     page.done();
  message: waiting 60 sec to load NY vaccine
   
- name: vaccinenyc
  url: https://www1.nyc.gov/site/doh/covid/covid-19-data-vaccines.page
