state: OH

links:
- name: vaccine
  url: https://coronavirus.ohio.gov/wps/portal/gov/covid-19/dashboards/covid-19-vaccine/covid-19-vaccination-dashboard
  overseerScript: |
      page.manualWait();
      await page.waitForDelay(60000);
      page.done();
  message: waiting 60 sec to load OH vaccine

- name: vaccine_secondary
  url: https://vaccine.coronavirus.ohio.gov
  overseerScript: |
      page.manualWait();
      await page.waitForDelay(60000);
      page.done();
  message: waiting 60 sec to load OH vaccine secondary
 
