state: RI

links:
- name: vaccine
  url: https://ri-department-of-health-covid-19-data-rihealth.hub.arcgis.com/

- name: vaccine_secondary
  url: https://ri-department-of-health-covid-19-response-vaccine-data-rihealth.hub.arcgis.com
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();
  message: wait for RI vaccine
