state: SD

links:
- name: vaccine
  url: https://doh.sd.gov/COVID/Dashboard.aspx
  overseerScript: |
    await page.waitForDelay(25000);
    await page.waitForSelector("i[title='Next Page']");
    await page.evaluate(() => {
      document.evaluate("//span[contains(text(),'Vaccines')]", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.setAttribute("ctpclickhere", "ctpclickhere");
    });
    page.click("span[ctpclickhere]");
    await page.waitForDelay(25000);
    page.done();
  message: navigating to "vaccines" tab of dash
  
- name: vaccineproviders
  url: https://doh.sd.gov/COVID/Vaccine/VaccineProviders.aspx
