state: AL

links:
- name: primary
  url: https://alpublichealth.maps.arcgis.com/apps/opsdashboard/index.html#/6d2771faa9da4a2786a509d82c8cf0f7
  overseerScript: |
    await page.waitForNavigation({
     waitUntil:"domcontentloaded"});
    await page.waitForSelector("span:nth-of-type(14)");
    page.click("span:nth-of-type(14)");
    await page.waitForDelay(1000);
    page.done();
  message: clicking on tab 12 (number 14)

- name: secondary
  url: https://alpublichealth.maps.arcgis.com/apps/opsdashboard/index.html#/6d2771faa9da4a2786a509d82c8cf0f7
  overseerScript: |
    await page.waitForNavigation({
     waitUntil:"domcontentloaded"});
    await page.waitForSelector("span:nth-of-type(15)");
    page.click("span:nth-of-type(15)");
    await page.waitForDelay(1000);
    page.done();
  message: clicking on tab 13 (number 15)

- name: tertiary
  url: https://alpublichealth.maps.arcgis.com/home/item.html?id=0c2185b8174646979f4abb5a45ef05c3&sublayer=3#data

- name: quaternary
  url: https://alpublichealth.maps.arcgis.com/home/item.html?id=0c2185b8174646979f4abb5a45ef05c3&sublayer=1#data

- name: quinary
  url: https://alpublichealth.maps.arcgis.com/home/item.html?id=015fd1e0d8074840ab624243a74c54c9&sublayer=1#data

- name: deaths_ethnicity
  url: https://alpublichealth.maps.arcgis.com/home/item.html?id=015fd1e0d8074840ab624243a74c54c9&sublayer=1#data
