state: DC

links:
- name: primary
  eval: True
  url: (date.today() - timedelta(days=1)).strftime("https://coronavirus.dc.gov/sites/default/files/dc/sites/coronavirus/page_content/attachments/COVID-19-Data-for-%B-%-d-%Y.xlsx")
  file: xlsx
  message: downloading xlsx for DC
