state: FL

links: 
- name: primary
  url: http://ww11.doh.state.fl.us/comm/_partners/covid19_report_archive/cases-monitoring-and-pui-information/state-report/state_reports_latest.pdf

- name: secondary
  url: https://floridahealthcovid19.gov/

