state: IA

links: 
- name: primary
  url: https://coronavirus.iowa.gov/pages/case-counts
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();

- name: secondary
  url: https://coronavirus.iowa.gov/pages/outcome-analysis-deaths
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(30000);
    page.done();

