state: OK

links:
- name: primary
  url: https://coronavirus.health.ok.gov/

- NAME: secondary
  url: https://looker-dashboards.ok.gov/embed/dashboards/75

- name: tertiary
  url: https://looker-dashboards.ok.gov/embed/dashboards/76
