state: WV

links: 
- name: primary
  url: https://dhhr.wv.gov/COVID-19/Pages/default.aspx

- name: secondary
  url: https://dhhr.wv.gov/Coronavirus%20Disease-COVID-19/Pages/default.aspx
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(40000);
    await page.evaluate(() => {
      document.evaluate("//button/span[contains(text(),'Cumulative Summary')]", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.setAttribute("ctpclickhere", "ctpclickhere");
    });
    page.click("span[ctpclickhere]");
    await page.waitForDelay(60000);
    page.done();
  requestSettings:
    maxWait: 120000
  message: clicking on Cumulative Summary tab of dashboard
